site_name: '@pnp/spfx-property-controls'
nav:
  - Home: 'index.md'
  - Controls:
    - PropertyFieldCodeEditor: 'controls/PropertyFieldCodeEditor.md'
    - PropertyFieldCollectionData: 'controls/PropertyFieldCollectionData.md'
    - PropertyFieldColorPicker: 'controls/PropertyFieldColorPicker.md'
    - PropertyFieldDateTimePicker: 'controls/PropertyFieldDateTimePicker.md'
    - PropertyFieldEnterpriseTermPicker: 'controls/PropertyFieldEnterpriseTermPicker.md'
    - PropertyFieldListPicker: 'controls/PropertyFieldListPicker.md'
    - PropertyFieldMessage: 'controls/PropertyFieldMessage.md'
    - PropertyFieldMultiSelect: 'controls/PropertyFieldMultiSelect.md'
    - PropertyFieldNumber: 'controls/PropertyFieldNumber.md'
    - PropertyFieldOrder: 'controls/PropertyFieldOrder.md'
    - PropertyFieldPassword: 'controls/PropertyFieldPassword.md'
    - PropertyFieldPeoplePicker: 'controls/PropertyFieldPeoplePicker.md'
    - PropertyFieldSearch: 'controls/PropertyFieldSearch.md'
    - PropertyFieldSitePicker: 'controls/PropertyFieldSitePicker.md'
    - PropertyFieldSpinButton: 'controls/PropertyFieldSpinButton.md'
    - PropertyFieldSpinner: 'controls/PropertyFieldSpinner.md'
    - PropertyFieldSwatchColorPicker: 'controls/PropertyFieldSwatchColorPicker.md'
    - PropertyFieldTermPicker: 'controls/PropertyFieldTermPicker.md'
    - PropertyFieldViewPicker: 'controls/PropertyFieldViewPicker.md'
    - PropertyPaneMarkdownContent: 'controls/PropertyPaneMarkdownContent.md'
    - PropertyPanePropertyEditor: 'controls/PropertyPanePropertyEditor.md'
    - PropertyPaneWebPartInformation: 'controls/PropertyPaneWebPartInformation.md'
  - 'Controls with callout':
    - PropertyFieldButtonWithCallout: 'controls/PropertyFieldButtonWithCallout.md'
    - PropertyFieldCheckboxWithCallout: 'controls/PropertyFieldCheckboxWithCallout.md'
    - PropertyFieldChoiceGroupWithCallout: 'controls/PropertyFieldChoiceGroupWithCallout.md'
    - PropertyFieldDropdownWithCallout: 'controls/PropertyFieldDropdownWithCallout.md'
    - PropertyFieldLabelWithCallout: 'controls/PropertyFieldLabelWithCallout.md'
    - PropertyFieldLinkWithCallout: 'controls/PropertyFieldLinkWithCallout.md'
    - PropertyFieldSliderWithCallout: 'controls/PropertyFieldSliderWithCallout.md'
    - PropertyFieldTextWithCallout: 'controls/PropertyFieldTextWithCallout.md'
    - PropertyFieldToggleWithCallout: 'controls/PropertyFieldToggleWithCallout.md'
  - Helpers:
    - PropertyPaneHelpers: 'helpers/PropertyPaneHelpers.md'
  - 'Beta testing': 'beta.md'
  - About:
    - 'Release notes': 'about/release-notes.md'
    - License: 'about/license.md'
  - 'Project Guides': 'guides'
theme:
  name: 'material'
  palette:
    primary: 'teal'
  logo: 'assets/pnp-spfx-controls.svg'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/m365pnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/pnp/sp-dev-fx-property-controls
edit_uri: blob/master/docs/documentation/docs
